# Generated by Django 4.2.2 on 2023-06-18 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название комнаты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Комната активен')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Звук'), ('voice', 'Голосовое')], default='text', max_length=255, verbose_name='Тип сообщения')),
                ('text_message', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Текст сообщения')),
                ('file_message', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Файл сообщения')),
                ('readers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Кто прочитал')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='Chat.chatroom', verbose_name='Комната сообщения')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
